name: Sync to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # important for mirroring

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BITBUCKET_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts

      - name: Add Bitbucket remote
        run: |
          git remote add bitbucket git@bitbucket.org/thapasachin572/test-bitbucket-repo3.git

      - name: Push to Bitbucket
        run: |
          git push bitbucket main --force
